<?php

function bxdev_reader_tools_init(){
	// session_destroy();
}

/**
 * Implementation of hook_menu().
 */
function bxdev_reader_tools_menu(){
	$items = array();
	
	$items['admin/reader-tools/check-session'] = array(
		'page callback' => 'bxdev_reader_tools_check_session',
		'access arguments' => array('access content'),
		'type' => MENU_CALLBACK,
	);
	
	$items['admin/reader-tools/check-password'] = array(
		'page callback' => 'bxdev_reader_tools_check_password',
		'page arguments' => array(3),
		'access arguments' => array('access content'),
		'type' => MENU_CALLBACK,
	);
	
	$items['admin/extras/reader-tools-password'] = array(
		'title' => t('Reader tools password'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array('bxdev_reader_tools_password_form'),
		'access arguments' => array('access administration pages'),
		'weight' => 50,
		'type' => NORMAL_MENU_ITEM,
	);
	
	return $items;
}

/**
 * Page callback: Reader Tools check session
 */
function bxdev_reader_tools_check_session(){
	// check if the reader tools session exists
	if(isset($_SESSION['reader_tools_password']) && $_SESSION['reader_tools_password'] == TRUE){
		print 'success';
	}else{
		print 'fail';
	}
}

/**
 * Page callback: Reader Tools check password
 */
function bxdev_reader_tools_check_password($password){
	if($password == variable_get('reader_tools_password', '')){
		$_SESSION['reader_tools_password'] = TRUE;
		print 'success';
	}else{
		print 'fail';
	}
}

/**
 * Form: Reader Tools password
 */
function bxdev_reader_tools_password_form(){
	$form['reader_tools_password'] = array(
		'#type' => 'textfield',
		'#title' => t('Password'),
		'#default_value' => variable_get('reader_tools_password', ''),
	);	
	return system_settings_form($form);
}